version: "3.9"
services:

  # postgres database
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank

  # golang app
  api:
    build:
      # . means current root folder (workdir)
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    # when using entrypoint like this ^, cmd command in Dockerfile is ignored
    # so we need to specify it using command:
    command: [ "/app/main" ]
