version: '3.9'

services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - java_network
  redis:
    container_name: redis
    image: redit:latest
    ports:
      - 6379:6379
    networks:
      - java_network
  java_docker:
    container_name: java-docker
    image: java-docker:1.0
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mongo
    environment:
      - NAME=docker
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - java_network

networks:
  java_network:
    name: java_network